name: Generate Data
on:
  schedule: 
    - cron: 0/5 * * * *
  workflow_dispatch:

jobs:
  generate_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Run PowerShell Data Generator
        run: pwsh -File generatedata.ps1
      - name: Commit and Push
        uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: '*'
